137 eer diagram
bierproductie/management pull request #148
Opened 2020-10-30 09:34 UTC by kepet19

2020-10-30 12:50 UTC, Kechr requested changes

2020-10-30 12:50 UTC, Kechr commented on project_report/tex/design.tex
> +configured in the databse in figure \ref{figure:eer_diagram_batch}.
databse -> database

2020-10-30 12:50 UTC, Kechr commented on project_report/tex/design.tex
> +The data is useful for making a completesystem for Refslevbæk Bryghus A/S,
completesystem -> complete system

2020-10-30 12:50 UTC, Kechr commented on project_report/tex/design.tex
> +For example if a person would like to know what happened then the beer got produced,
add comma after example

2020-10-30 12:50 UTC, Kechr commented on project_report/tex/design.tex
> +How much was defect out of the totalt amount produced.
totalt -> total

2020-10-30 16:11 UTC, Kechr requested changes

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +The data that should be stored in the database is a batch.
"The data that should be stored in the database is a batch. "

I think we need to be more specific about this. It's not exactly a batch we store, but all information from a batch. (from the beer production machine)

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +You can see how the data should be stored in /
Please refrain from using personal pronouns. 
This can be changed to something like "It can be seen how... "

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +The data is useful for making a complete system for Refslevbæk Bryghus A/S,
Well, the data itself is not useful when making a complete system, how we handle the information is.

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +The Batch's database is used in the system to keep track of batch's.
Just database. Batches don't have their own database :)
".. track of batches."

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +For example, if a person would like to know what happened then the beer got produced,
then -> when (I assume?)
got -> was

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +like what temperature was it then the temperature was highest, Did that ruin it.
"... like what temperature was it then the temperature was highest,"
change to:
"... like what the highest temperature was during the production ..."


"... , Did that ruin it."
Change to:
"... , did that have a negative effect on the beer."

2020-10-30 16:11 UTC, Kechr commented on project_report/tex/design.tex
> +How much was defect out of the total amount produced.
Maybe change to:
"How many products were defect?"

2020-11-06 12:48 UTC, Kechr requested changes

2020-11-06 12:48 UTC, Kechr commented on project_report/tex/design.tex
> +what and how the data should be stored in the database.
Add \\ at the end of the line

2020-11-06 12:48 UTC, Kechr commented on project_report/tex/design.tex
> +The database is used in the system to keep track of data that resembles a batch's.
Repeating line 5&6.

2020-11-06 12:48 UTC, Kechr commented on project_report/tex/design.tex
> +For example, if a person would like to know what happened then the beer was produced,
then > when

2020-11-06 12:48 UTC, Kechr commented on project_report/tex/design.tex
> +like what the highest temperature was it during the production, Did that have a
Capital D to lower case.

2020-11-06 12:49 UTC, Joergenson requested changes

2020-11-06 12:49 UTC, Joergenson commented on project_report/tex/design.tex
> +The database is used in the system to keep track of data that resembles a batch's.
line 09 batch's -> batch or batch's data

2020-11-06 12:49 UTC, Joergenson commented on project_report/tex/design.tex
> +like what the highest temperature was it during the production, Did that have a
11-13 need rephrasing  :^)

2020-11-06 14:14 UTC, Kechr approved these changes

2020-11-06 14:17 UTC, merged