add inital implementation of the database
bierproductie/management pull request #238
Opened 2020-12-12 13:23 UTC by kepet19

2020-12-12 14:32 UTC, Kechr requested changes
I suspect these are just notes?

2020-12-12 14:51 UTC, Bokaiii requested changes

2020-12-12 14:51 UTC, Bokaiii commented on project_report/tex/implementation.tex
> +handle by the REST API. The REST API has been taking inspiration from the EER
handled

2020-12-13 16:27 UTC, nymann commented
Updated

2020-12-13 20:35 UTC, merged